/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Frame;
/**
 *
 * @author akilajwasala
 */
public class MP3PlayerGUI1 extends javax.swing.JFrame {
    MainClass MC = new MainClass();
    AnimationClass AC = new AnimationClass();

    public static int count;

    int xMouse;
    int yMouse;

    int width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 185;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height - 180;
    /**
     * Creates new form MP3PlayerGUI1
     */
    public MP3PlayerGUI1(java.awt.Frame parent, boolean modal) 
    {
        
        //super(parent, modal);
        initComponents();
        slideShow();
        
        this.setLocation(width, height);
    }
    
    public void slideShow(){   
        new Thread(){
            public void run(){
                try{
                    while(true){
                        switch(count){
                            case 0:                                
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -490, 20, 2, Background1lbl);
                                AC.jLabelXLeft(500, 0, 20, 2, Background2lbl);
                                
                                count = 1;
                                break;
                                
                            case 1:                   
                                Thread.sleep(3000);
                                AC.jLabelXRight(-490, 0, 20, 2, Background1lbl);
                                AC.jLabelXRight(0, 500, 20, 2, Background2lbl);
                                
                                count = 0;
                                break;
                        }
                    }
                    
                }catch(Exception e){
                    System.out.println("Error");
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblminimize = new javax.swing.JLabel();
        lblclose = new javax.swing.JLabel();
        SelectFile = new javax.swing.JLabel();
        Pause = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();
        Stop = new javax.swing.JLabel();
        Loop = new javax.swing.JLabel();
        LoopCounter = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        list2 = new javax.swing.JLabel();
        list1 = new javax.swing.JLabel();
        lblremove = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        Backgroundlable = new javax.swing.JLabel();
        Background2lbl = new javax.swing.JLabel();
        Background1lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AjMp3 Player");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 735));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 735));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 3, 30, 30));

        lblclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 3, 30, 30));

        SelectFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SelectFileMouseReleased(evt);
            }
        });
        jPanel1.add(SelectFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 50, 50));

        Pause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PauseMouseReleased(evt);
            }
        });
        jPanel1.add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 70, 80));

        Play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleased(evt);
            }
        });
        jPanel1.add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, 100));

        Stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StopMouseReleased(evt);
            }
        });
        jPanel1.add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 70));

        Loop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoopMouseReleased(evt);
            }
        });
        jPanel1.add(Loop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 50));

        LoopCounter.setForeground(new java.awt.Color(204, 204, 255));
        LoopCounter.setText("Loop off ");
        jPanel1.add(LoopCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Display.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        Display.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 440, 30));
        jPanel1.add(list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 260, 20));

        list1.setFont(new java.awt.Font("Minion Pro", 0, 18)); // NOI18N
        list1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 260, 20));

        lblremove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 90, 90));

        lbladd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbladd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdMouseClicked(evt);
            }
        });
        jPanel1.add(lbladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 100, 90));

        Backgroundlable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Background.png"))); // NOI18N
        Backgroundlable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundlableMouseDragged(evt);
            }
        });
        Backgroundlable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundlableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackgroundlableMouseReleased(evt);
            }
        });
        jPanel1.add(Backgroundlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        Background2lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Background2.png"))); // NOI18N
        jPanel1.add(Background2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        Background1lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Background1.png"))); // NOI18N
        jPanel1.add(Background1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleased
        MC.Stop();
        MC.Resume();
    }//GEN-LAST:event_PlayMouseReleased

    private void PauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PauseMouseReleased
        MC.Pause();
    }//GEN-LAST:event_PauseMouseReleased

    private void SelectFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectFileMouseReleased
        FileFilter filter = new FileNameExtensionFilter("MP3 files","mp3","mpeg3","mp4");
        
        JFileChooser chooser = new JFileChooser("//Users//akilajwasala//Music");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            MC.Stop();
            
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            
            String name = chooser.getSelectedFile().getName();
            Display.setText(name);
            
            MC.Play(song);
        }
    }//GEN-LAST:event_SelectFileMouseReleased

    private void StopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseReleased
        MC.Stop();
    }//GEN-LAST:event_StopMouseReleased

    private void LoopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoopMouseReleased
        switch(count){
            case 0:
                count = 1;
                LoopCounter.setText("Loop on");
                break;
            
            case 1:
                count = 0;
                LoopCounter.setText("Loop off");
                break; 
        }
    }//GEN-LAST:event_LoopMouseReleased

    private void BackgroundlableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundlableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundlableMouseReleased

    private void BackgroundlableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundlableMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BackgroundlableMousePressed

    private void BackgroundlableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundlableMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BackgroundlableMouseDragged

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void lblminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeMouseClicked
        // TODO add your handling code here:
        this.setState(MP3PlayerGUI1.ICONIFIED);
    }//GEN-LAST:event_lblminimizeMouseClicked

    private void lbladdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdMouseClicked
        FileFilter filter = new FileNameExtensionFilter("MP3 files","mp3","mpeg3","mp4");
        
        JFileChooser chooser = new JFileChooser("//Users//akilajwasala//Desktop");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            MC.Stop();
            
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            
            String name = chooser.getSelectedFile().getName();
            list1.setText(name);
       
            
            MC.Play(song);
            Display.setText(name);
        }
    }//GEN-LAST:event_lbladdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MP3PlayerGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                try{
                    Thread.sleep(3000);
                }catch(Exception e){
                    
                }
                
                MP3PlayerGUI1 dialog = new MP3PlayerGUI1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1lbl;
    private javax.swing.JLabel Background2lbl;
    private javax.swing.JLabel Backgroundlable;
    public static javax.swing.JLabel Display;
    private javax.swing.JLabel Loop;
    private javax.swing.JLabel LoopCounter;
    private javax.swing.JLabel Pause;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel SelectFile;
    private javax.swing.JLabel Stop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblminimize;
    private javax.swing.JLabel lblremove;
    private javax.swing.JLabel list1;
    private javax.swing.JLabel list2;
    // End of variables declaration//GEN-END:variables
}
